import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';
import { useAuth } from '../context/AuthContext';
import { Toaster } from 'react-hot-toast';
import {
  BillIcon, PaymentHistoryIcon, CarWashStatusIcon, CalendarCheckIcon, DashboardIcon, WashIcon
} from '../components/CarWashIcons';
import { PageLoader } from '../components/Loaders';

const MODULES = [
  { label: 'New Bill',        icon: <BillIcon />,           path: '/billing/new',          light: '#1d4ed8', dark: '#3b82f6', desc: 'Create a wash bill' },
  { label: 'Payment History', icon: <PaymentHistoryIcon />, path: '/billing/history',       light: '#059669', dark: '#10b981', desc: 'View all transactions' },
  { label: 'Vehicle Status',  icon: <CarWashStatusIcon />,  path: '/vehicles/status',       light: '#b45309', dark: '#f59e0b', desc: 'Live wash queue' },
  { label: 'My Attendance',   icon: <CalendarCheckIcon />,  path: '/employees/attendance',  light: '#1e40af', dark: '#60a5fa', desc: 'Daily check-in/out' },
];

export default function EmployeeDashboard() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    setLoading(true);
    api.get('/dashboard/employee-summary')
      .then(r => setData(r.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <PageLoader text="Loading dashboard..." />;
  if (!data) return null;

  const clockInTime = data.attendance?.clock_in ? new Date(data.attendance.clock_in).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : null;
  const isCheckedIn = !!data.attendance && !data.attendance.clock_out;

  return (
    <div className="fade-in">
      <Toaster position="top-center" />
      <div className="page-header">
        <div>
          <h2>Welcome back, {user?.name}</h2>
          <p>Here's what's happening today</p>
        </div>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon blue"><DashboardIcon /></div>
          <div className="stat-info">
            <h4>My Bills Today</h4>
            <div className="stat-value">{data.todayBills}</div>
            <div className="stat-sub">Bills generated by you</div>
          </div>
        </div>
        
        <div className="stat-card">
          <div className="stat-icon amber"><WashIcon /></div>
          <div className="stat-info">
            <h4>Queue Status</h4>
            <div className="stat-value">{data.pendingWash}</div>
            <div className="stat-sub">Vehicles currently washing</div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon green"><CalendarCheckIcon /></div>
          <div className="stat-info">
            <h4>Attendance Status</h4>
            {isCheckedIn ? (
              <>
                <div className="stat-value" style={{ color: 'var(--success)' }}>Clocked In</div>
                <div className="stat-sub">Since {clockInTime}</div>
              </>
            ) : (
              <>
                <div className="stat-value" style={{ color: 'var(--text-tertiary)' }}>Clocked Out</div>
                <div className="stat-sub">Not currently checked in</div>
              </>
            )}
          </div>
        </div>
      </div>

      <div style={{ marginTop: 28, marginBottom: 16 }}>
        <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>Quick Actions</h3>
        <p style={{ margin: '3px 0 0', fontSize: '0.82rem', color: 'var(--text-tertiary)' }}>Access your modules instantly</p>
      </div>
      
      <div className="qa-grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))' }}>
        {MODULES.map(mod => (
          <div
            key={mod.path}
            className="qa-card"
            style={{ '--qa-light': mod.light, '--qa-dark': mod.dark }}
            onClick={() => navigate(mod.path)}
          >
            <div className="qa-icon-wrap">
              {mod.icon}
            </div>
            <div>
              <div className="qa-label">{mod.label}</div>
              <div className="qa-desc">{mod.desc}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
